name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.2
  - seaborn=0.12.2
  - pandas=1.5.2
  - pip=20.3.3
  - pandas-profiling=3.5.0
  - pyarrow=9.0
  - pip:
      - wandb==0.15.4
