name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.1.2
  - requests=2.31.0
  - mlflow=2.4.1
  - scikit-learn=1.2.2
  - pip:
      - wandb==0.15.4
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
