name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.4.1
  - ipython=8.12.0
  - notebook=6.5.4
  - jupyterlab=3.5.2
  - cookiecutter=2.1.1
  - hydra-core=1.3.0
  - matplotlib=3.7.1
  - pandas=2.0.2
  - git=2.30.2
  - pip=23.1.2
  - pip:
      - wandb==0.15.4
