name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.0.2
  - pip=23.1.2
  - mlflow=2.4.1
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pillow=9.4.0
  - pip:
      - wandb==0.15.4
